"""
The corpus: the books' extracted text on disk, one file per article.

The extractor turns a PDF page range into a list of *marker lines* — plain
strings, each optionally opening with a ``\\x02``-prefixed marker (heading,
bullet, checkbox, value-table row …) and carrying bold/italic as ``\\x04``…
``\\x07`` sentinels. That list is the whole hand-off between the two halves
of the generator, and this module writes it out and reads it back, so that:

- the text can be **inspected** and diffed (``git diff`` after a change to the
  extractor shows exactly which lines moved);
- a **translation** can be the same file with the same tag skeleton, checked
  line for line against the English;
- the wiki can be **built without the PDFs** — a checkout carries the text,
  which is CC BY-SA 4.0, while the PDFs never leave the GM's disk.

Layout::

    extracted/
      book1/
        articles.json        the book's article list, in build order
        harm-healing.txt     one file per article, named by slug
        the-ranger.txt
      book2/
        ...

File format — one line per marker line, ``TAG<tab>payload``::

    # Harm & Healing · Book I, pp. 41–48
    PAGE	41
    H2	Death's Door
    P	When you are reduced to 0 HP, …
    VR	Bronze knife	2
    BOX

``P`` is plain body text; every other tag is a marker's name (``MARKERS`` in
``text.py``). A marker that carries a payload always has the tab, even when
the payload is empty; a bare marker (``BOX``, ``HR``) never does. A
``\\x03`` sub-field separator inside a payload becomes a further tab.
``PAGE`` lines are not markers: they say which PDF page the lines below sit
on. Lines opening ``#`` and blank lines are ignored.

Inside a payload, bold and italic are ``<b>``…``</b>`` and ``<i>``…``</i>``;
a literal backslash, tab, newline or ``<`` is escaped ``\\\\``, ``\\t``,
``\\n``, ``\\<``. Nothing else is ever escaped, so the text reads as the
book prints it.

The files are **build output**, regenerated by ``--extract``. A fix to the
text belongs in the extractor; a hand edit here is undone by the next
extraction and shows up as a diff.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from . import REPO_ROOT
from .text import B_OFF, B_ON, I_OFF, I_ON, M_SEP, MARKERS

CORPUS_DIRNAME = "extracted"
MANIFEST_NAME = "articles.json"

TEXT_TAG = "P"
PAGE_TAG = "PAGE"
PAYLOAD_TAGS = frozenset(tag for tag, m in MARKERS.items() if m.endswith(" "))
BARE_TAGS = frozenset(MARKERS) - PAYLOAD_TAGS
_MARKER_TAGS = {m.rstrip(" "): tag for tag, m in MARKERS.items()}

# Article kinds that have a text file. Hubs and the maps page are made at
# build time from the article list alone.
TEXT_KINDS = frozenset({"article", "arcana"})

_FMT_OUT = {B_ON: "<b>", B_OFF: "</b>", I_ON: "<i>", I_OFF: "</i>"}
_FMT_IN = {v: k for k, v in _FMT_OUT.items()}
_ESC_OUT = {"\\": "\\\\", "\t": "\\t", "\n": "\\n", "<": "\\<"}
_ESC_IN = {"\\": "\\", "t": "\t", "n": "\n", "<": "<"}
_DECODE_RE = re.compile(r"\\(.)|</?[bi]>|<")
_TAG_RE = re.compile(r"^[A-Z][A-Z0-9]*$")


class CorpusError(ValueError):
    """A corpus file that does not parse, or a round trip that does not hold."""


def corpus_dir(root: Path | None = None) -> Path:
    return (root or REPO_ROOT) / CORPUS_DIRNAME


def book_dir(corpus: Path, book_id: str) -> Path:
    return corpus / book_id


def text_path(corpus: Path, art: dict) -> Path:
    return book_dir(corpus, art["book"]) / f"{art['slug']}.txt"


# ---------------------------------------------------------------- payloads

def encode_text(s: str) -> str:
    """Inline sentinels to tags, the four escapable characters escaped."""
    out = []
    for ch in s:
        if ch in _FMT_OUT:
            out.append(_FMT_OUT[ch])
        elif ch in _ESC_OUT:
            out.append(_ESC_OUT[ch])
        else:
            out.append(ch)
    return "".join(out)


def decode_text(s: str, where: str = "") -> str:
    """Inverse of ``encode_text``. A bare ``<`` is an error, not a guess."""
    def repl(m: re.Match) -> str:
        tok = m.group(0)
        if tok[0] == "\\":
            esc = m.group(1)
            if esc not in _ESC_IN:
                raise CorpusError(f"{where}: unknown escape {tok!r}")
            return _ESC_IN[esc]
        if tok in _FMT_IN:
            return _FMT_IN[tok]
        raise CorpusError(f"{where}: bare '<' (write it as '\\<')")
    return _DECODE_RE.sub(repl, s)


def encode_line(line: str) -> str:
    """One marker line → one file line (``TAG<tab>payload``)."""
    if line.startswith("\x02"):
        head, _sp, payload = line.partition(" ")
        tag = _MARKER_TAGS.get(head)
        if tag is None or (tag in BARE_TAGS and _sp):
            raise CorpusError(f"unregistered marker {line[:12]!r}")
        if tag in BARE_TAGS:
            return tag
        parts = payload.split(M_SEP)
    else:
        tag = TEXT_TAG
        parts = line.split(M_SEP)
    return tag + "\t" + "\t".join(encode_text(p) for p in parts)


def decode_line(file_line: str, where: str = "") -> str:
    """One file line → one marker line."""
    tag, *parts = file_line.split("\t")
    if not _TAG_RE.match(tag):
        raise CorpusError(f"{where}: no tag on {file_line[:40]!r}")
    if tag == TEXT_TAG:
        if not parts:
            raise CorpusError(f"{where}: text line without a tab")
        return M_SEP.join(decode_text(p, where) for p in parts)
    if tag in BARE_TAGS:
        if parts:
            raise CorpusError(f"{where}: {tag} takes no payload")
        return MARKERS[tag]
    if tag in PAYLOAD_TAGS:
        if not parts:
            raise CorpusError(f"{where}: {tag} needs a tab (payload may be empty)")
        return MARKERS[tag] + M_SEP.join(decode_text(p, where) for p in parts)
    raise CorpusError(f"{where}: unknown tag {tag!r}")


# ------------------------------------------------------------------- files

def dump_text(lines: list[str], pages: list[int], header: str = "") -> str:
    """The file body for one article: ``PAGE`` lines where the page turns."""
    if len(lines) != len(pages):
        raise CorpusError("lines and pages differ in length")
    out: list[str] = []
    if header:
        out.extend("# " + h if h else "#" for h in header.splitlines())
    cur = None
    for ln, pg in zip(lines, pages):
        if pg != cur:
            out.append(f"{PAGE_TAG}\t{pg}")
            cur = pg
        out.append(encode_line(ln))
    return "\n".join(out) + "\n"


def parse_text(text: str, where: str = "") -> tuple[list[str], list[int]]:
    """Inverse of ``dump_text``: ``(lines, pages)``."""
    lines: list[str] = []
    pages: list[int] = []
    page = 0
    for n, raw in enumerate(text.split("\n"), 1):
        if not raw or raw.startswith("#"):
            continue
        here = f"{where}:{n}"
        if raw.startswith(PAGE_TAG + "\t"):
            try:
                page = int(raw[len(PAGE_TAG) + 1:])
            except ValueError:
                raise CorpusError(f"{here}: bad page number") from None
            continue
        lines.append(decode_line(raw, here))
        pages.append(page)
    return lines, pages


def _header(art: dict) -> str:
    pages = (
        f"p. {art['start_page']}"
        if art["start_page"] == art.get("end_page")
        else f"pp. {art['start_page']}–{art['end_page']}"
    )
    half = f" ({art['half']})" if art.get("half") else ""
    return (
        f"{art['title']} · {art.get('book_label') or art['book']}, {pages}{half}\n"
        "Generated by the extractor — fix the extractor, not this file."
    )


def write_book(
    corpus: Path,
    book: dict,
    page_count: int,
    articles: list[dict],
    texts: dict[str, tuple[list[str], list[int]]],
) -> int:
    """Write one book's manifest and text files; verify each round trip.

    Text files the book no longer names are removed, so a renamed slug leaves
    no orphan. Returns the number of text files written.
    """
    bdir = book_dir(corpus, book["id"])
    bdir.mkdir(parents=True, exist_ok=True)
    manifest = {
        "book": book["id"],
        "label": book["label"],
        "title": book.get("title") or book["label"],
        "filename": book["filename"],
        "page_count": page_count,
        "articles": articles,
    }
    (bdir / MANIFEST_NAME).write_text(
        json.dumps(manifest, ensure_ascii=False, indent=1) + "\n",
        encoding="utf-8",
        newline="\n",
    )
    keep: set[str] = set()
    n = 0
    for art in articles:
        if art["kind"] not in TEXT_KINDS:
            continue
        lines, pages = texts[art["slug"]]
        path = text_path(corpus, art)
        body = dump_text(lines, pages, _header(art))
        back = parse_text(body, str(path))
        if back != (lines, pages):
            raise CorpusError(f"{path}: does not round-trip")
        path.write_text(body, encoding="utf-8", newline="\n")
        keep.add(path.name)
        n += 1
    for stale in bdir.glob("*.txt"):
        if stale.name not in keep:
            stale.unlink()
    return n


def has_book(corpus: Path, book_id: str) -> bool:
    return (book_dir(corpus, book_id) / MANIFEST_NAME).is_file()


def read_book(
    corpus: Path, book_id: str
) -> tuple[dict, list[dict], dict[str, tuple[list[str], list[int]]]]:
    """One book back off disk: ``(manifest, articles, texts)``."""
    bdir = book_dir(corpus, book_id)
    mpath = bdir / MANIFEST_NAME
    try:
        manifest = json.loads(mpath.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        raise CorpusError(f"{mpath}: {e}") from None
    articles = manifest.get("articles") or []
    texts: dict[str, tuple[list[str], list[int]]] = {}
    for art in articles:
        if art["kind"] not in TEXT_KINDS:
            continue
        path = text_path(corpus, art)
        try:
            body = path.read_text(encoding="utf-8")
        except OSError:
            raise CorpusError(f"{path}: missing (re-run with --extract)") from None
        texts[art["slug"]] = parse_text(body, str(path))
    return manifest, articles, texts
